"""Stable serialization and fixture headers for the conformance generator."""

from __future__ import annotations

import json
import os
import sys
import tempfile
import unicodedata
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
SEED = 20260929
ALPHABET = tuple(map(ord, "abcdefgh0123,.ΑΒΓабв漢字永和かなカナ한글，、。→✓☺😀🙂\u1200"))
# Generated from the original app's UI modules until WP-701; now verified against FROZEN.sha256 only.
FROZEN_FILES = (
    "languages/covers-well.json",
    "languages/languages.json",
    "languages/phrases.json",
    "naming/family-names.json",
    "text/ignorable.json",
    "text/visible-chars.json",
)


def header(category: str, sources: list[str], *, seed: int | None = None) -> dict:
    import fontTools
    import unicodedata2

    import fpengine

    return {
        "generator": "tools/conformance/generate.py",
        "generator_version": 1,
        "category": category,
        "fpengine_version": fpengine.__version__,
        "fonttools_version": fontTools.version,
        "unicodedata2_version": unicodedata2.unidata_version,
        "python_unicodedata_version": unicodedata.unidata_version,
        "python": f"{sys.version_info.major}.{sys.version_info.minor}",
        "sources": sources,
        # Only frozen fixtures name the original app here; live ones never did.
        "reference": None,
        "seed": seed,
        "note": "Generated by `make conformance`. Never edit by hand.",
    }


def fixture(category: str, sources: list[str], *, seed: int | None = None, **values) -> dict:
    return {"header": header(category, sources, seed=seed), **values}


def _pretty(value: Any, level: int = 0) -> str:
    def scalar(item: Any) -> str:
        return json.dumps(item, ensure_ascii=False, allow_nan=False)

    indent = "  " * level
    if isinstance(value, dict):
        if not value:
            return "{}"
        rows = [f"{indent}  {scalar(key)}: {_pretty(item, level + 1)}" for key, item in value.items()]
        return "{\n" + ",\n".join(rows) + "\n" + indent + "}"
    if isinstance(value, (tuple, list)):
        if all(not isinstance(item, (dict, list, tuple)) for item in value):
            return "[" + ", ".join(scalar(item) for item in value) + "]"
        return "[\n" + ",\n".join(f"{indent}  {_pretty(item, level + 1)}" for item in value) + "\n" + indent + "]"
    return scalar(value)


def write_bytes(path: Path, data: bytes) -> None:
    if path.is_file() and path.read_bytes() == data:
        print(f"unchanged {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary_path = None
    try:
        with tempfile.NamedTemporaryFile(dir=path.parent, prefix=f".{path.name}.", delete=False) as temporary:
            temporary_path = Path(temporary.name)
            temporary.write(data)
            temporary.flush()
            os.fsync(temporary.fileno())
        os.replace(temporary_path, path)
    finally:
        if temporary_path is not None:
            temporary_path.unlink(missing_ok=True)
    print(f"wrote {path}")


def dump(path: Path, value: dict) -> None:
    write_bytes(path, (_pretty(value) + "\n").encode("utf-8"))
