"""Regenerate the JSON conformance contract and its matching Swift script table."""

from __future__ import annotations

import argparse
import hashlib
import importlib
import traceback
from pathlib import Path

import swift_tables
from common import FROZEN_FILES, ROOT, dump, write_bytes

CATEGORIES = ("scripts", "planner", "naming", "shaping")
README = """# Generated conformance fixtures

Generated by `make conformance`. Never hand-edit these files.

| File | Behavior | Consumer |
| --- | --- | --- |
| scripts/group-ranges.json | Unicode script groups, labels and covered groups | WP-301 |
| planner/cases.json | Priority, rules and source assignments | WP-302 |
| languages/languages.json | Language tables, samples and constants (frozen) | WP-301 |
| languages/covers-well.json | Language coverage thresholds and markers (frozen) | WP-301 |
| languages/phrases.json | Missing languages, descriptions and sample lines (frozen) | WP-301/302 |
| text/ignorable.json | Ignorable Unicode code points (frozen) | WP-301 |
| text/visible-chars.json | Visible Unicode code points in sample text (frozen) | WP-301 |
| naming/family-names.json | Suggested family, style and file names (frozen) | WP-304 |
| naming/postscript_names.json | Unique PostScript names | WP-304 |
| shaping/ot_alternatives.json | OpenType alternatives (generated after WP-107) | WP-301/304 |

The same run writes `Packages/FontPlaygroundKit/Sources/FPCore/Generated/ScriptGroupTable.swift`.
Use `make conformance-check` to detect drift in both trees. JSON scalar arrays are
compact; objects and nested arrays use two-space indentation. Headers record
versions, sources and the fixed random seed without timestamps or host paths.

Files marked frozen were generated from the original app's UI logic, which WP-701
removed at v1.0.0. `FROZEN.sha256` protects their exact bytes; the generator only
verifies them. The Swift code is now the canonical implementation of that logic,
and these files are its regression goldens. Engine-derived fixtures and the Swift
table continue to regenerate normally.
"""


def _frozen_error(relative: str) -> ValueError:
    return ValueError(f"conformance: frozen fixture changed: {relative} (frozen at WP-701; never hand-edit)")


def _verify_frozen(out: Path) -> None:
    manifest = out / "FROZEN.sha256"
    if not manifest.is_file():
        raise _frozen_error("FROZEN.sha256")
    listed = {}
    for line in manifest.read_text(encoding="utf-8").splitlines():
        digest, relative = line.split("  ", 1)
        listed[relative] = digest
    # A dropped manifest line would silently unfreeze its file, so the set itself is checked.
    unexpected = sorted(set(FROZEN_FILES) ^ set(listed))
    if unexpected:
        raise _frozen_error(unexpected[0])
    for relative, digest in listed.items():
        path = out / relative
        if not path.is_file() or hashlib.sha256(path.read_bytes()).hexdigest() != digest:
            raise _frozen_error(relative)
    print(f"frozen: {len(listed)} files verified")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=ROOT / "spec/fixtures")
    parser.add_argument("--swift-out", type=Path, default=ROOT / "Packages/FontPlaygroundKit/Sources/FPCore/Generated")
    parser.add_argument("--only", choices=CATEGORIES)
    args = parser.parse_args(argv)
    try:
        _verify_frozen(args.out)
        selected = set(CATEGORIES if args.only is None else ("scripts", args.only))
        for category in CATEGORIES:
            if category not in selected:
                continue
            module = importlib.import_module(f"categories.{category}")
            if category == "shaping":
                module.generate(args.out)
                continue
            files = module.generate()
            for relative, value in files.items():
                dump(args.out / relative, value)
            for path in sorted((args.out / category).glob("*.json")):
                relative = path.relative_to(args.out).as_posix()
                if relative not in files and relative not in FROZEN_FILES:
                    path.unlink()
        write_bytes(args.out / "README.md", README.encode("utf-8"))
        return swift_tables.main(
            [str(args.out / "scripts/group-ranges.json"), str(args.swift_out / "ScriptGroupTable.swift")]
        )
    except Exception:
        traceback.print_exc()
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
