"""Emit the Foundation-only script lookup arrays; this module uses only the standard library."""

import argparse
import json
from pathlib import Path

from common import write_bytes


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    parser.add_argument("destination", type=Path)
    args = parser.parse_args(argv)
    data = json.loads(args.source.read_text(encoding="utf-8"))
    starts = [f"0x{start:06X}" for start, _, _ in data["ranges"]]
    groups = [str(data["groups"].index(group)) for _, _, group in data["ranges"]]
    lines = [
        "// swift-format-ignore-file",
        "// Generated by tools/conformance/swift_tables.py from spec/fixtures/scripts/group-ranges.json. Do not edit.",
        "",
        "/// Script group of every Unicode scalar: `groups[i]` applies from `starts[i]` up to `starts[i + 1] - 1`",
        "/// (the last run ends at U+10FFFF). A group number indexes the fixture's groups in GROUPS order.",
        "enum ScriptGroupTable {",
    ]
    for name, kind, values in (("starts", "UInt32", starts), ("groups", "UInt8", groups)):
        lines.append(f"  static let {name}: [{kind}] = [")
        lines.extend("    " + ", ".join(values[index : index + 8]) + "," for index in range(0, len(values), 8))
        lines.append("  ]")
    lines.append("}")
    write_bytes(args.destination, ("\n".join(lines) + "\n").encode("utf-8"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
