"""The Python-generated contract consumed by the Foundation-only Swift ports."""

from __future__ import annotations

import hashlib
import importlib.util
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

from fpengine.naming import postscript_name
from fpengine.planner import plan, source_of
from fpengine.records import expand, ranges
from fpengine.scripts import GROUP_IDS, LABELS, group_of, groups_covered
from fpengine.spec import ForgeSpec, MaterialSpec
from tests.fixtures import fake_face

ROOT = Path(__file__).resolve().parents[3]
TOOLS = ROOT / "tools/conformance"
FIXTURES = ROOT / "spec/fixtures"
JSON_FILES = {
    "scripts/group-ranges.json",
    "planner/cases.json",
    "languages/languages.json",
    "languages/covers-well.json",
    "languages/phrases.json",
    "naming/family-names.json",
    "naming/postscript_names.json",
    "text/ignorable.json",
    "text/visible-chars.json",
}
FROZEN_FILES = {
    name for name in JSON_FILES if name.startswith(("languages/", "text/")) or name == "naming/family-names.json"
}
FROZEN_MESSAGE = "conformance: frozen fixture changed: {} (frozen at WP-701; never hand-edit)"
HEADER_KEYS = {
    "generator",
    "generator_version",
    "category",
    "fpengine_version",
    "fonttools_version",
    "unicodedata2_version",
    "python_unicodedata_version",
    "python",
    "sources",
    "reference",
    "seed",
    "note",
}


def run_generator(out, swift, *arguments, seed="0"):
    return subprocess.run(
        [
            sys.executable,
            str(TOOLS / "generate.py"),
            "--out",
            str(out),
            "--swift-out",
            str(swift),
            *map(str, arguments),
        ],
        capture_output=True,
        text=True,
        env={**os.environ, "PYTHONHASHSEED": seed},
        timeout=30,
    )


def assert_success(result):
    assert result.returncode == 0, result.stdout + result.stderr


def tree(path):
    return {file.relative_to(path).as_posix(): file.read_bytes() for file in path.rglob("*") if file.is_file()}


def read(out, relative):
    return json.loads((out / relative).read_text(encoding="utf-8"))


def seed_frozen(out):
    """The generator cannot recreate frozen fixtures, so an output tree starts from the committed ones."""
    for relative in (*FROZEN_FILES, "FROZEN.sha256"):
        (out / relative).parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(FIXTURES / relative, out / relative)
    return out


@pytest.fixture(scope="module")
def generated(tmp_path_factory):
    directory = tmp_path_factory.mktemp("conformance")
    out, swift = seed_frozen(directory / "fixtures"), directory / "swift"
    assert_success(run_generator(out, swift))
    return out, swift


def test_fixture_files_and_headers(generated):
    out, swift = generated
    expected = JSON_FILES | {"README.md", "FROZEN.sha256"}
    if importlib.util.find_spec("fpengine.shaping") is not None:
        expected.add("shaping/ot_alternatives.json")
    assert set(tree(out)) == expected
    assert set(tree(swift)) == {"ScriptGroupTable.swift"}
    for relative in JSON_FILES:
        value = read(out, relative)
        assert next(iter(value)) == "header"
        header = value["header"]
        assert set(header) == HEADER_KEYS
        assert header["generator_version"] == 1
        assert header["category"] == relative.removesuffix(".json")
        assert header["python"] == f"{sys.version_info.major}.{sys.version_info.minor}"
        assert header["seed"] in (None, 20260929)
        assert (header["reference"] is None) == (relative not in FROZEN_FILES)
        assert header["sources"] and header["note"] == "Generated by `make conformance`. Never edit by hand."
        raw = (out / relative).read_bytes()
        assert raw.endswith(b"\n") and b"\r" not in raw
        assert str(ROOT).encode() not in raw


def test_generator_is_deterministic(generated, tmp_path):
    out, swift = generated
    other_out, other_swift = seed_frozen(tmp_path / "fixtures"), tmp_path / "swift"
    assert_success(run_generator(other_out, other_swift, seed="1"))
    assert tree(out) == tree(other_out)
    assert tree(swift) == tree(other_swift)
    original = {p: p.stat().st_mtime_ns for root in (other_out, other_swift) for p in root.rglob("*") if p.is_file()}
    result = run_generator(other_out, other_swift)
    assert_success(result)
    # WP-107 owns shaping serialization and may replace its file even for identical bytes.
    assert all(p.stat().st_mtime_ns == stamp for p, stamp in original.items() if p.parent.name != "shaping")
    assert "unchanged" in result.stdout


def test_script_group_ranges_cover_every_code_point(generated):
    data = read(generated[0], "scripts/group-ranges.json")
    assert data["groups"] == list(GROUP_IDS) and data["labels"] == LABELS
    cursor, previous = 0, None
    for start, end, group in data["ranges"]:
        assert start == cursor and start <= end and group != previous
        assert all(group_of(cp) == group for cp in range(start, end + 1))
        cursor, previous = end + 1, group
    assert cursor == 0x110000
    chars = "a1,éΩдبאनก한あ漢，、→☺€😀\u1200"
    groups = ["latin"] * 4 + [
        "greek",
        "cyrillic",
        "arabic",
        "hebrew",
        "indic",
        "southeast_asian",
        "hangul",
        "kana",
        "han",
        "cjk_symbols",
        "cjk_symbols",
        "symbols",
        "symbols",
        "symbols",
        "emoji",
        "other",
    ]
    assert data["samples"] == [[ord(char), group] for char, group in zip(chars, groups, strict=True)]
    assert len(data["groups_covered"]) == 17
    for case in data["groups_covered"]:
        assert case["expected"] == groups_covered(expand(case["codepoints"]))


def test_swift_table_matches_json(generated):
    data = read(generated[0], "scripts/group-ranges.json")
    swift = (generated[1] / "ScriptGroupTable.swift").read_text()
    assert swift.startswith("// swift-format-ignore-file\n")
    for name, expected in (
        ("starts", [row[0] for row in data["ranges"]]),
        ("groups", [data["groups"].index(row[2]) for row in data["ranges"]]),
    ):
        body = re.search(rf"static let {name}: \[UInt\d+\] = \[(.*?)\]", swift, re.S).group(1)
        lines = [line.strip().removesuffix(",").split(", ") for line in body.splitlines() if line.strip()]
        assert all(len(line) == 8 for line in lines[:-1])
        assert [int(value, 0) for line in lines for value in line] == expected


def test_conformance_check_covers_generated_swift():
    makefile = (ROOT / "Makefile").read_text()
    path = "Packages/FontPlaygroundKit/Sources/FPCore/Generated"
    assert f"git diff --exit-code -- spec/fixtures {path}" in makefile
    assert f"git ls-files --others --exclude-standard -- spec/fixtures {path}" in makefile


def test_planner_cases(generated):
    cases = read(generated[0], "planner/cases.json")["cases"]
    assert len(cases) >= 71
    reference_names = {
        "test_priority_order_wins_without_rules",
        "test_rule_overrides_priority",
        "test_rule_falls_back_when_material_lacks_char",
        "test_assignments_are_disjoint_and_complete",
        "test_source_of_prefers_the_rule_font_when_it_has_the_character",
        "test_source_of_falls_back_to_priority_order_then_none",
        "test_source_of_agrees_with_the_plan",
    }
    assert reference_names <= {case["name"] for case in cases}
    values = {value for case in cases for value in case["rules"].values()}
    assert {None, -1, 7} <= values
    assert any(len(case["coverages"]) in case["rules"].values() for case in cases)
    for case in cases:
        coverages = [expand(coverage) for coverage in case["coverages"]]
        assert any(cp not in set().union(*coverages) for cp, _ in case["queries"])
        assert case["queries"] == [[cp, source_of(cp, coverages, case["rules"])] for cp, _ in case["queries"]]
        spec = ForgeSpec(materials=[MaterialSpec(fake_face(cps)) for cps in coverages], script_rules=case["rules"])
        actual = plan(spec)
        assert case["assignments"] == [ranges(actual.assignments[index]) for index in range(len(coverages))]


def test_postscript_name_fixtures(generated):
    cases = read(generated[0], "naming/postscript_names.json")["cases"]
    inputs = [(family, style) for family, style, _ in cases]
    assert len(inputs) == len(set(inputs)) and len(inputs) >= 300
    worked = [
        "AvenirNextPingFangFP61d27706-Regular",
        "AvenirNextFP76fdbbf4-Regular",
        "ForgedFP5ef09893-Regular",
        "ForgedFP4f4f31c7-Regular",
        "NotoFP193bc651-Regular",
        "NotoFP39174c89-Regular",
        "ForgedFP4baff28f-Regular",
        "ForgedFP865d96ec-Regular",
        "MyFontFP072c765b-BoldItalic",
        "MyFontFP3601e1d1-BoldItalic",
        "ForgedTestFP373d14cc-Regular",
        "AVeryLongFamilyNameThatKeepsGoinFP4bedb3c1-ExtraCondensedSemibo",
    ]
    assert [row[2] for row in cases[:12]] == worked
    assert {(family, "Regular") for family in ("", "Café", "Cafe\u0301", "　Noto ")} <= set(inputs)
    assert ("Fixture Sans", "Bold ") in inputs and ("A" * 80, "Regular") in inputs
    # Each script contributes generated names; no category may accidentally use an empty alphabet.
    assert {group_of(ord(char)) for family, _ in inputs for char in family if char != " "} >= set(GROUP_IDS)
    for family, style, expected in cases:
        assert expected == postscript_name(family, style)
        assert len(expected) <= 63 and re.fullmatch(r"[A-Za-z0-9]+-[A-Za-z0-9]+", expected)


def test_generator_removes_stale_files(generated, tmp_path):
    out, swift = tmp_path / "fixtures", tmp_path / "swift"
    shutil.copytree(generated[0], out)
    old = out / "planner/old.json"
    old.write_text("{}")
    stale_name = out / "naming/old.json"
    stale_name.write_text("{}")
    sentinel = out / "shaping/foreign.json"
    sentinel.parent.mkdir(exist_ok=True)
    sentinel.write_bytes(b"unowned\n")
    (out / "languages/retired.json").write_text("preserved")
    readme = (out / "README.md").read_bytes()
    assert_success(run_generator(out, swift))
    assert not old.exists() and not stale_name.exists()
    assert (out / "naming/family-names.json").read_bytes() == (FIXTURES / "naming/family-names.json").read_bytes()
    assert sentinel.read_bytes() == b"unowned\n"
    assert (out / "languages/retired.json").read_text() == "preserved"
    assert (out / "README.md").read_bytes() == readme


def test_only_category_generates_its_own_script_prerequisite(tmp_path):
    out, swift = seed_frozen(tmp_path / "fixtures"), tmp_path / "swift"
    assert_success(run_generator(out, swift, "--only", "planner"))
    frozen = FROZEN_FILES | {"FROZEN.sha256"}
    assert set(tree(out)) == frozen | {"README.md", "scripts/group-ranges.json", "planner/cases.json"}
    assert (swift / "ScriptGroupTable.swift").is_file()


def test_frozen_fixtures_are_verified_not_regenerated(generated):
    out = generated[0]
    assert all((out / name).read_bytes() == (FIXTURES / name).read_bytes() for name in FROZEN_FILES)
    manifest = (FIXTURES / "FROZEN.sha256").read_text(encoding="utf-8")
    assert manifest == "".join(
        f"{hashlib.sha256((FIXTURES / name).read_bytes()).hexdigest()}  {name}\n" for name in sorted(FROZEN_FILES)
    )
    result = run_generator(out, generated[1])
    assert_success(result)
    assert result.stdout.count(f"frozen: {len(FROZEN_FILES)} files verified") == 1
    assert "frozen (reference/ removed)" not in result.stdout


def test_frozen_fixture_change_is_rejected(generated, tmp_path):
    out, swift = tmp_path / "fixtures", tmp_path / "swift"
    shutil.copytree(generated[0], out)
    path = out / "languages/languages.json"
    data = bytearray(path.read_bytes())
    data[-2] ^= 1
    path.write_bytes(bytes(data))
    planner = (out / "planner/cases.json").read_bytes()
    (out / "planner/cases.json").write_text("stale")
    result = run_generator(out, swift)
    assert result.returncode == 1
    assert FROZEN_MESSAGE.format("languages/languages.json") in result.stderr
    # Verification runs before any write.
    assert (out / "planner/cases.json").read_text() == "stale" and not swift.exists()
    path.unlink()
    result = run_generator(out, swift)
    assert result.returncode == 1 and FROZEN_MESSAGE.format("languages/languages.json") in result.stderr
    shutil.copyfile(generated[0] / "languages/languages.json", path)
    (out / "planner/cases.json").write_bytes(planner)
    assert_success(run_generator(out, swift))


def test_frozen_manifest_must_list_every_frozen_fixture(generated, tmp_path):
    out, swift = tmp_path / "fixtures", tmp_path / "swift"
    shutil.copytree(generated[0], out)
    manifest = out / "FROZEN.sha256"
    lines = manifest.read_text(encoding="utf-8").splitlines(keepends=True)
    manifest.write_text("".join(line for line in lines if not line.endswith("  text/ignorable.json\n")))
    result = run_generator(out, swift)
    assert result.returncode == 1 and FROZEN_MESSAGE.format("text/ignorable.json") in result.stderr
    manifest.unlink()
    result = run_generator(out, swift)
    assert result.returncode == 1 and FROZEN_MESSAGE.format("FROZEN.sha256") in result.stderr


def test_writer_is_compact_atomic_and_rejects_nan(tmp_path):
    sys.path.insert(0, str(TOOLS))
    from common import dump

    path = tmp_path / "test.json"
    dump(path, {"scalar_array": [1, "é", None], "nested": [[32, 126]], "fraction": 0.1})
    before = path.read_bytes()
    assert b'"scalar_array": [1, "\xc3\xa9", null]' in before
    assert b'"nested": [\n    [32, 126]\n  ]' in before
    with pytest.raises(ValueError):
        dump(path, {"invalid": float("nan")})
    assert path.read_bytes() == before and set(tmp_path.iterdir()) == {path}
